import fs from 'node:fs';
import { products, productById, availableProductPdf } from './product-data.mjs';
import { partnerContent, solutions } from './portfolio-data.mjs';

// Body template deliberately reuses the established portfolio classes and shared shell.
export function renderProduct(p, {shell,hero,section,list,link,e,actions,steps,partner,partnerLink}) {
  const vendor=partner(p.partner);
  const context={partner:p.partner,solution:p.primarySolution,product:p.id};
  const pdf=availableProductPdf(p);
  const download=pdf?`<a href="${e(pdf)}" download aria-label="Download PDF: ${e(p.name)}">Download PDF <span class="sr-only">for ${e(p.name)}</span></a>`:'';
  const primarySolution=solutions.find(s=>s.id===p.primarySolution);
  const parts={
    hero:hero({title:p.name,intro:p.intro,eyebrow:'PRODUCT GUIDE',crumbs:[['cybersecurity.html','Solutions'],[`${primarySolution.id}.html`,primarySolution.name],[null,p.name]],context,logo:vendor}).replace('Discuss My Requirements','Discuss Requirements'),
    overview:section('fit','YOUR REQUIREMENT','Where this product fits',`<div class="pf-split"><div><h3>Business problems addressed</h3>${list(p.problems)}</div><aside class="pf-callout"><h3>Suitable customer situations</h3><p>${e(p.suitable)}</p><p>${e(p.evaluate)}</p></aside></div>`),
    capabilities:section('capabilities','CAPABILITIES AND BOUNDARIES','What to evaluate before purchasing',`<div class="pf-split"><div><h3>Verified capability overview</h3>${list(p.capabilities)}<p>${link('#references','Official sources for these capabilities')}</p></div><div><h3>Important limitations</h3>${list(p.limitations)}<p class="pf-note">Confirm the exact edition, supported versions and entitlement in your quote. Product coverage is not an ITSIPL service guarantee.</p></div></div>`,true),
    workflow:section('how-it-works','HOW IT WORKS','From setup to everyday use',`<div class="pf-grid pf-three">${p.how.map((text,i)=>`<article class="pf-card"><p class="pf-kicker">Step ${i+1}</p><h3>${['Prepare the scope','Apply the protection or workflow','Validate and operate'][i]}</h3><p>${e(text)}</p></article>`).join('')}</div>`),
    purchase:section('compatibility','EXISTING SYSTEMS AND LICENSING','Check the proposed configuration',`<div class="pf-grid pf-three">${[['Platform and deployment',p.platform],['Integration considerations',p.integration],['Licensing considerations',p.licensing]].map(([title,text])=>`<article class="pf-card"><h3>${e(title)}</h3><p>${e(text)}</p></article>`).join('')}</div><p class="pf-note">A capability overview cannot confirm compatibility with your estate. Bring version numbers, current contracts and required integrations to the selection discussion.</p>`,true),
    budget:section('budget','BUDGET DRIVERS','Request a configuration-based quote',`<p class="pf-intro">${e(p.budget)}</p>${list(['Separate product subscriptions, one-time delivery work and recurring services in the proposal.','Use your actual scope and planned growth; compare options using the same acceptance requirements.','Check renewal dates and avoid replacing compatible systems before the business case is clear.'])}`),
    itsipl:section('itsipl-role','WORK WITH ITSIPL','Selection, purchasing and agreed delivery',`<p class="pf-intro">ITSIPL is a multi-vendor reseller and solution provider. Our existing portfolio covers solution design, implementation and support. Agree product-specific delivery tasks and service boundaries before ordering.</p>${steps}<p class="pf-note">For ${e(p.name)}, start with this acceptance check: ${e(p.evaluate)} Training, monitoring hours, response targets and specialist incident response require express agreement.</p>` ,true),
    alternatives:section('alternatives','A BALANCED SHORTLIST','Relevant alternatives and complementary options',`<p class="pf-intro">${e(p.alternativeNote||'Use the same business requirement to compare these options. Deployment, channel or workload coverage and operational responsibilities differ; the product name alone is not a selection criterion.')}</p><div class="pf-grid">${p.alternatives.map(id=>{const alt=productById(id);return `<article class="pf-card"><p class="pf-kicker">${e(alt.need)}</p><h3>${link(alt.page,alt.name)}</h3><p>${e(alt.suitable)}</p><p><strong>Selection check:</strong> ${e(alt.limitations[0])}</p></article>`;}).join('')}</div><div class="pf-related">${p.solutions.map(id=>{const s=solutions.find(s=>s.id===id);return link(`${id}.html`,`${s.name} selection guide`);}).join('')}${link(`partner-${p.partner}.html`,`${vendor.name} local portfolio guide`)}${partnerLink(p.partner,`Explore ${vendor.name} with ITSIPL →`)}</div>`),
    faq:section('faq','PRODUCT QUESTIONS',`${p.name}: common buying questions`,`<div class="pf-grid">${p.faqs.map(([q,a])=>`<article class="pf-card"><h3>${e(q)}</h3><p>${e(a)}</p></article>`).join('')}</div>`,true),
    references:section('references','OFFICIAL REFERENCES','Check the vendor documentation',`<ul class="pf-link-list">${p.references.map(([label,url])=>`<li>${link(url,label)}</li>`).join('')}</ul><p class="pf-note">Content reviewed <time datetime="${p.reviewDate}">5 October 2026</time>. This is an ITSIPL buying guide, not a vendor-issued specification. Features, supported versions and subscriptions can change. ${pdf?'The optional PDF is an existing ITSIPL summary and may have an earlier review date.':''}</p>${download?`<div class="pf-related">${download}</div>`:''}`),
    enquiry:section('next-step','YOUR NEXT STEP',`Discuss ${p.name} with ITSIPL`, `<div class="pf-cta"><p>${e(partnerContent[p.partner].prepare)} Mention the required product edition, desired outcome and what must remain compatible.</p>${actions(context).replace('Discuss My Requirements','Discuss Requirements')}${download?`<div class="pf-related">${download}</div>`:''}<p class="pf-note">The quote should identify licences, delivery owner, acceptance criteria and support scope. ${link('mailto:sales@itsipl.com','Email sales@itsipl.com')} for a requirements discussion.</p></div>`,true)
  };
  let body=fs.readFileSync('templates/product-body.html','utf8');
  for(const [key,value] of Object.entries(parts))body=body.replace(`{{${key}}}`,value);
  return shell(`${p.name}: Product Guide & Selection`,`${p.name} through ITSIPL: suitable uses, capabilities, limitations, compatibility, licensing and budget factors. Explore the guide and request a quote.`,p.page,body);
}

export function renderProductComparison(s,{section,e,link}) {
 const shortlist=products.filter(p=>p.solutions.includes(s.id));
 return section('compare-products','COMPARE THE APPROACH','Choose by fit, existing systems and operating effort',`<p class="pf-intro">${e(s.decision)}</p><div class="pf-grid">${shortlist.map(p=>`<article class="pf-card"><h3>${link(p.page,p.name)}</h3><p><strong>Choose to address:</strong> ${e(p.need)}.</p><p><strong>Suitable situation:</strong> ${e(p.suitable)}</p><p><strong>Check against existing systems:</strong> ${e(p.platform)}</p><p><strong>Budget drivers:</strong> ${e(p.budget)}</p><p><strong>Boundary:</strong> ${e(p.limitations[0])}</p></article>`).join('')}</div><p class="pf-note">Compare licences at equivalent scope. Keep compatible systems where they meet the requirement, and use a representative pilot to verify the shortlisted configuration. Detailed capabilities and FAQs are in the linked product guides.</p>`);
}
